### ISSUE TITLE
Epic: Protocol 23 Changes

### ISSUE THREAD

**Issue by Shaptic** [stellar/stellar-rpc#267]
# Protocol 23

**Scope:** This epic defines work as it pertains to Stellar RPC + the SDKs.
**General Overview:** [Platform scoping doc](https://docs.google.com/document/d/1uiy-H_H60X7B41YoBUAzNkZqjuKC_SAaPjDB-RQBRcE/)
**References**: Platform's issues for Protocol 23: [projects/37#32](https://github.com/orgs/stellar/projects/37/views/32).

----------------------------------

All work should target the feature branch: [`protocol-23`](https://github.com/stellar/stellar-rpc/tree/protocol-23).

## Dimension 1: Independent Work
This is work we need to do in this release irrespective of the protocol changes.

- [x] https://github.com/stellar/stellar-rpc/issues/373
- [x] https://github.com/stellar/stellar-rpc/issues/379
- [x] https://github.com/stellar/stellar-rpc/issues/358

## Dimension 2: Protocol Work

This phase involves adding support for all of the plumbing we'll need for the actual feature work:

- [x] Generate new protocol definitions:
  * [x] Update Horizon to use new XDR
  * [x] Update RPC to use the new XDR
  * [x] Update the JS SDK to use the new XDR

### State Archival 
- [x] Add support for Core's `/getledgerentry` endpoint
- [x] https://github.com/stellar/stellar-rpc/issues/367
- [x] https://github.com/stellar/stellar-rpc/issues/370
- [x] https://github.com/stellar/soroban-rpc/pull/264
- [x] https://github.com/stellar/stellar-rpc/issues/368
- [x] https://github.com/stellar/stellar-rpc/issues/369

### Unified Events 
- [x] #387

### After Core's RC
- [x] https://github.com/stellar/stellar-rpc/issues/372
- [x] https://github.com/stellar/stellar-rpc/issues/386
- [x] https://github.com/stellar/stellar-rpc/issues/385

## Dimension 3: Downstream

This phase encompasses impact to SDKs and beyond once RPC schemas are locked in:
  * [x] **JavaScript SDK:**
    - [x] Bump XDR
    - [x] Add strkey support
    - [x] Add any new RPC API fields or request parameters
  * [ ] Inform Dev X, Freighter, Lab, et al. about upcoming changes.
  * [x] Prepare a blast for community SDKs that includes all XDR and RPC changes.

**Comment by ahmedfemoo** [comment]
Pi network to the moon
