### ISSUE TITLE
[epic] rename soroban-rpc to stellar-rpc

### ISSUE THREAD

**Issue by mollykarcher** [stellar/stellar-rpc#62]
### What problem does your feature solve?

With the launch of Soroban, we are looking to create a unified RPC across Stellar and Soroban. Note that this issue is intended to cover exclusively the work to logistically rename the product. If there are actually features that we want to be added _prior_ to executing the rename, those will be captured separately and block this work.

### What would you like to see?

`s/soroban-rpc/stellar-rpc/g`

This should happen anywhere that this might be referenced, including but not limited to:
- [ ] this repository
- [ ] any other repos in the stellar org that reference rpc (tools, go, kube, quickstart, system-test, helm-charts, etc etc)
- [ ] build artifacts generated from this repository
- [ ] external or internal documentation

We will probably want to release one last version of the `soroban-rpc` binary with a deprecation warning, pointing them to the new `stellar-rpc` binary.

Blocked by #110 
```[tasklist]
### Tasks
- [ ] https://github.com/stellar/soroban-rpc/issues/301
- [ ] https://github.com/stellar/soroban-rpc/issues/302
- [ ] https://github.com/stellar/soroban-rpc/issues/304
- [ ] https://github.com/stellar/soroban-rpc/issues/307
- [ ] https://github.com/stellar/soroban-rpc/issues/306
```

**Comment by mollykarcher** [comment]
Let's consider issues binaries/docker images with both names for p22

**Comment by psheth9** [comment]
https://github.com/stellar/ops/issues/3237#issuecomment-2355209718 -- ops request
